//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _300_Tarefas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tarefa
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Tarefa")]
        public string Nome { get; set; }
        [Display(Name = "Concluído")]
        public bool Concluido { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
